"""
Django settings for fann project.
Generated by 'django-admin startproject' using Django 5.0.2.
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# --------------------------------------------------
# BASE
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = "django-insecure-1&o1=q0)g1+$g@n*eqovrrd+#1$uwq=l!ar^g^!vmh4_$3t0&1"
DEBUG = True

IN_DOCKER = os.getenv("IN_DOCKER", "0") == "1"

# --------------------------------------------------
# HOSTS / CORS
# --------------------------------------------------
ALLOWED_HOSTS = [
    "apifann.globaltechserivce.com",
    "tryfann.com",
    "www.tryfann.com",
    "app.globaltechserivce.com",
    "www.app.globaltechserivce.com",
    "localhost",
    "127.0.0.1",
    "api.fann.art",
    "app.fann.art",
    "859f258773eb.ngrok-free.app",
]

CORS_ORIGIN_ALLOW_ALL = True

# --------------------------------------------------
# APPS
# --------------------------------------------------
INSTALLED_APPS = [
    "daphne",  # MUST BE FIRST

    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "channels",
    "django_crontab",

    "fann.users.apps.UsersConfig",
    "fann.buyer.apps.BuyerConfig",
    "fann.notifications.apps.NotificationsConfig",
    "fann.chat.apps.ChatConfig",
    "fann.artist.apps.ArtistConfig",
    "fann.analysisai.apps.AnalysisaiConfig",
    "fann.market_final.apps.MarketFinalConfig",
]
# --------------------------------------------------
# MIDDLEWARE
# --------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

# --------------------------------------------------
# TEMPLATES
# --------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# --------------------------------------------------
# ASGI / CHANNELS
# --------------------------------------------------
ASGI_APPLICATION = "core.asgi.application"

REDIS_SCHEME = os.getenv("REDIS_SCHEME", "redis")
REDIS_HOST = os.getenv("REDIS_HOST", "redis" if IN_DOCKER else "127.0.0.1")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
REDIS_DB = int(os.getenv("REDIS_DB", "0"))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "")

if REDIS_PASSWORD:
    REDIS_URL = f"{REDIS_SCHEME}://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"
else:
    REDIS_URL = f"{REDIS_SCHEME}://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [REDIS_URL],
        },
    },
}

# --------------------------------------------------
# DATABASE
# --------------------------------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# --------------------------------------------------
# CELERY (FIXED — NO LOCALHOST)
# --------------------------------------------------
CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    "redis://redis:6379/1" if IN_DOCKER else "redis://127.0.0.1:6379/1",
)

CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    "redis://redis:6379/2" if IN_DOCKER else "redis://127.0.0.1:6379/2",
)

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# --------------------------------------------------
# AUTH / REST
# --------------------------------------------------
AUTH_USER_MODEL = "users.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

# --------------------------------------------------
# CRON
# --------------------------------------------------
CRONJOBS = [
    ("* * * * *", "fann.artist.cron_jobs.sync_all_auction_statuses"),
    ("* * * * *", "fann.artist.cron_jobs.sync_all_event_statuses"),
]

# --------------------------------------------------
# SECURITY
# --------------------------------------------------
CSRF_TRUSTED_ORIGINS = [
    "https://fann.globaltechserivce.com",
    "https://www.fann.globaltechserivce.com",
    "https://apifann.globaltechserivce.com",
    "https://tryfann.com",
    "https://api.fann.art",
]

CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# --------------------------------------------------
# EMAIL
# --------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
DEFAULT_FROM_EMAIL = "Sales@viko.world"
EMAIL_HOST = "live.smtp.mailtrap.io"          # correct host
EMAIL_HOST_USER = "api"
EMAIL_HOST_PASSWORD = "8214d0a7136a55332e6b5bc39fe8534c"
EMAIL_PORT = 587
EMAIL_USE_TLS = True                     # must be True for port 587

# Base URL of the frontend, used to build links in transactional emails
# (e.g. the email-verification link). Override per environment.
FRONTEND_BASE_URL = "https://app.globaltechserivce.com"

EMAIL_SUBJECT_PREFIX = "[FANN] "
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", "errors@fann.example.com")

# --------------------------------------------------
# STATIC / MEDIA
# --------------------------------------------------
STATIC_URL = "/static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# --------------------------------------------------
# I18N
# --------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# --------------------------------------------------
# DEFAULTS
# --------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# --------------------------------------------------
# MOONPAY
# --------------------------------------------------
MOONPAY_PUBLISHABLE_KEY = "pk_test_2SGsOonicrgIdoEkgHp3MFGQAY1Vnxc"
MOONPAY_SECRET_KEY = "sk_test_X1W79LJ33X3gjB4bsJK8RddXdN0oiZGW"
MOONPAY_WEBHOOK_KEY = "wk_test_43V53j8F2hl3Zh7Gph4bwJ35uMTPeG8"
MOONPAY_WIDGET_BASE = "https://buy-sandbox.moonpay.com"
MOONPAY_API_BASE = "https://api-sandbox.moonpay.com"






# """
# Django settings for fann project.
#
# Generated by 'django-admin startproject' using Django 5.0.2.
#
# For more information on this file, see
# https://docs.djangoproject.com/en/5.0/topics/settings/
#
# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.0/ref/settings/
# """
#
# from datetime import timedelta
# from pathlib import Path
# import os
# from fann import users
#
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
#
# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/
#
# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-1&o1=q0)g1+$g@n*eqovrrd+#1$uwq=l!ar^g^!vmh4_$3t0&1"
#
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
#
# ALLOWED_HOSTS = [
#     "apifann.globaltechserivce.com",
#     "tryfann.com",
#     "www.tryfann.com" "app.globaltechserivce.com",
#     "www.app.globaltechserivce.com",
#     "localhost",
#     "127.0.0.1",
#     "api.fann.art",
#     "app.fann.art",
#     "859f258773eb.ngrok-free.app"
# ]
# CORS_ORIGIN_ALLOW_ALL = True
#
# # Application definition
#
# INSTALLED_APPS = [
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "daphne",
#     "django.contrib.staticfiles",
#     "rest_framework",
#     "rest_framework_simplejwt",
#     "corsheaders",
#     "channels",
#     "fann.users.apps.UsersConfig",
#     "fann.buyer.apps.BuyerConfig",
#     "fann.notifications.apps.NotificationsConfig",
#     "fann.chat.apps.ChatConfig",
#     "fann.artist.apps.ArtistConfig",
#     "django_crontab",
#     "fann.analysisai.apps.AnalysisaiConfig",
#     "fann.market_final.apps.MarketFinalConfig",
# ]
#
# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "corsheaders.middleware.CorsMiddleware",
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]
#
# CORS_ALLOW_METHODS = [
#     "DELETE",
#     "GET",
#     "OPTIONS",
#     "PATCH",
#     "POST",
#     "PUT",
# ]
# ROOT_URLCONF = "core.urls"
#
# TEMP_DIR = os.path.join(BASE_DIR, "templates")
# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [TEMP_DIR],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#             ],
#         },
#     },
# ]
#
#
# ASGI_APPLICATION = "core.asgi.application"
#
# REDIS_SCHEME = os.getenv("REDIS_SCHEME", "redis")
# REDIS_HOST = os.getenv(
#     "REDIS_HOST",
#     "redis" if os.getenv("IN_DOCKER", "0") == "1" else "127.0.0.1",
# )
# REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
# REDIS_DB = int(os.getenv("REDIS_DB", "0"))
# REDIS_PASSWORD = os.getenv("REDIS_PASSWORD", "")
#
# if REDIS_PASSWORD:
#     REDIS_URL = os.getenv(
#         "REDIS_URL",
#         f"{REDIS_SCHEME}://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}",
#     )
# else:
#     REDIS_URL = os.getenv(
#         "REDIS_URL",
#         f"{REDIS_SCHEME}://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}",
#     )
#
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             # Use URL form; avoids localhost foot-guns inside containers
#             "hosts": [REDIS_URL],
#         },
#     },
# }
#
# MEDIA_URL = "/media/"
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
#
# CSRF_TRUSTED_ORIGINS = [
#     "https://*",
#     "https://fann.globaltechserivce.com",
#     "https://www.fann.globaltechserivce.com",
#     "https://apifann.globaltechserivce.com",
#     "https://tryfann.com",
#     "https://api.fann.art",
# ]
#
# CRONJOBS = [
#     ("* * * * *", "fann.artist.cron_jobs.sync_all_auction_statuses"),
#     ("* * * * *", "fann.artist.cron_jobs.sync_all_event_statuses"),
# ]
#
# CSRF_COOKIE_SECURE = True
# SESSION_COOKIE_SECURE = True
#
# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": (
#         "rest_framework_simplejwt.authentication.JWTAuthentication",
#     )
# }
#
# SIMPLE_JWT = {
#     "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),
#     "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
# }
#
# # Database
# # https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# import os
# from dotenv import load_dotenv
#
# load_dotenv()
#
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("DB_NAME"),
#         "USER": os.getenv("DB_USER"),
#         "PASSWORD": os.getenv("DB_PASSWORD"),
#         "HOST": os.getenv("DB_HOST"),
#         "PORT": os.getenv("DB_PORT"),
#     }
# }
#
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# DEFAULT_FROM_EMAIL = "Sales@fann.com"
# # EMAIL_HOST = "sandbox.smtp.mailtrap.io"
# # EMAIL_HOST_USER = "80b035a60ed665"
# # EMAIL_HOST_PASSWORD = "82995d9020e10f"
# # EMAIL_PORT = "2525"
#
# EMAIL_HOST = 'live.smtp.mailtrap.io'
# EMAIL_HOST_USER = 'api'
# EMAIL_HOST_PASSWORD = '8214d0a7136a55332e6b5bc39fe8534c'
# EMAIL_PORT = '587'
#
#
#
# SITE_URL = os.environ.get("SITE_URL", "https://app.globaltechserivce.com")
# FRONTEND_URL = os.environ.get("FRONTEND_URL", SITE_URL)
# # “From” address for outgoing emails
# # Optional but nice:
# EMAIL_SUBJECT_PREFIX = "[FANN] "
# SERVER_EMAIL = os.environ.get("SERVER_EMAIL", "errors@fann.example.com")
#
#
# AUTH_USER_MODEL = "users.User"
#
# # Password validation
# # https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
#
# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]
#
# # Internationalization
# # https://docs.djangoproject.com/en/5.0/topics/i18n/
#
# LANGUAGE_CODE = "en-us"
#
# TIME_ZONE = "UTC"
#
# USE_I18N = True
#
# USE_TZ = True
#
# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.0/howto/static-files/
#
#
# STATIC_URL = "/static/"
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, "static"),
# ]
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
#
# # Default primary key field type
# # https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
#
# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# CELERY_BROKER_URL = "redis://localhost:6379/0"
# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
#
# MOONPAY_PUBLISHABLE_KEY = "pk_test_2SGsOonicrgIdoEkgHp3MFGQAY1Vnxc"
# MOONPAY_SECRET_KEY = "sk_test_X1W79LJ33X3gjB4bsJK8RddXdN0oiZGW"  # server only
# MOONPAY_WEBHOOK_KEY = (
#     "wk_test_43V53j8F2hl3Zh7Gph4bwJ35uMTPeG8"  # webhook signing secret from dashboard
# )
# MOONPAY_WIDGET_BASE = "https://buy-sandbox.moonpay.com"  # sandbox
# MOONPAY_API_BASE = (
#     "https://api-sandbox.moonpay.com"  # sandbox api (or https://api.moonpay.com)
# )
