# Generated by Django 4.2.10 on 2025-08-04 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["timestamp"]},
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="buyer",
        ),
        migrations.RemoveField(
            model_name="chatroom",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
        migrations.AddField(
            model_name="chatroom",
            name="name",
            field=models.CharField(
                default=datetime.datetime(
                    2025, 8, 4, 16, 17, 51, 643688, tzinfo=datetime.timezone.utc
                ),
                max_length=255,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
