# Generated by Django 4.2.10 on 2025-08-11 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Art",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("image", models.FileField(blank=True, null=True, upload_to="arts/")),
                (
                    "art_type",
                    models.CharField(
                        choices=[("Fractional", "Fractional"), ("Single", "Single")],
                        default="Single",
                        help_text="Is this a fractional piece or a single-edition work?",
                        max_length=20,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_art",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("start_time", models.DateTimeField(help_text="When bidding opens")),
                ("end_time", models.DateTimeField(help_text="When bidding closes")),
                (
                    "starting_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum starting bid",
                        max_digits=20,
                    ),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum acceptable sale price (optional)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("live", "Live"),
                            ("ended", "Ended"),
                            ("canceled", "Canceled"),
                        ],
                        default="upcoming",
                        help_text="Current state of the auction",
                        max_length=10,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Winning bid amount (populated at close)",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "art",
                    models.OneToOneField(
                        help_text="Art piece being auctioned (must be purchase_type='auction')",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction",
                        to="artist.art",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist_auction",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who won the auction (set when auction ends)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_auctions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AuctionBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Bid amount in your chosen currency",
                        max_digits=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("withdrawn", "Withdrawn"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="active",
                        help_text="Current state of this bid",
                        max_length=10,
                    ),
                ),
                (
                    "auction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auction_bids",
                        to="artist.auction",
                    ),
                ),
                (
                    "bidder",
                    models.ForeignKey(
                        help_text="User who placed the bid",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-amount", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="auction",
            index=models.Index(
                fields=["status", "end_time"], name="artist_auct_status_ae61d7_idx"
            ),
        ),
    ]
