# Generated by Django 4.2.10 on 2025-08-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="hash",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="art",
            name="no_of_fraction",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
