# Generated by Django 4.2.10 on 2025-08-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0002_art_hash_art_no_of_fraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
