# Generated by Django 4.2.10 on 2025-08-21 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artist", "0003_art_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Paid", "Paid"),
                            ("In Progress", "In Progress"),
                            ("Fulfilled", "Fulfilled"),
                            ("Canceled", "Canceled"),
                            ("Refunded", "Refunded"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("Fiat", "Fiat"), ("Crypto", "Crypto")],
                        default="Fiat",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "platform_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "discount_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Authorized", "Authorized"),
                            ("Captured", "Captured"),
                            ("Refunded", "Refunded"),
                            ("Failed", "Failed"),
                        ],
                        default="Authorized",
                        max_length=12,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artist_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("comment", models.TextField()),
                (
                    "art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="artist.art"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "currency",
                    models.CharField(
                        choices=[("Fiat", "Fiat"), ("Crypto", "Crypto")],
                        default="Fiat",
                        max_length=10,
                    ),
                ),
                ("scheduled_for", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Processing", "Processing"),
                            ("Paid", "Paid"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["artist", "status", "scheduled_for"],
                        name="artist_payo_artist__89c49a_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[("Fiat", "Fiat"), ("Crypto", "Crypto")], max_length=12
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("Fiat", "Fiat"), ("Crypto", "Crypto")],
                        default="Fiat",
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Authorized", "Authorized"),
                            ("Captured", "Captured"),
                            ("Refunded", "Refunded"),
                            ("Failed", "Failed"),
                        ],
                        default="Authorized",
                        max_length=12,
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="artist.order",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "processed_at"],
                        name="artist_paym_status_ce932e_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["artist", "status"], name="artist_orde_artist__9134e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["artist", "created_at"], name="artist_orde_artist__e9132a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["payment_status", "paid_at"],
                name="artist_orde_payment_1c5139_idx",
            ),
        ),
    ]
