# Generated by Django 4.2.10 on 2025-08-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0005_artcomment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="art",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="artist.art",
            ),
        ),
    ]
