# Generated by Django 4.2.10 on 2025-08-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0006_order_art"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(
                choices=[
                    ("Upcoming", "Upcoming"),
                    ("Live", "Live"),
                    ("Ended", "Ended"),
                ],
                default="Upcoming",
                help_text="Current state of the auction",
                max_length=10,
            ),
        ),
    ]
