# Generated by Django 4.2.10 on 2025-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0007_alter_auction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="art_tags",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="art",
            name="dimensions",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="art",
            name="royalty",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="art",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
