# Generated by Django 4.2.10 on 2025-09-01 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artist", "0008_art_art_tags_art_dimensions_art_royalty_art_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owner_art",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
