# Generated by Django 4.2.10 on 2025-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0009_art_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
