# Generated by Django 4.2.10 on 2025-09-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0011_remove_art_owner_order_no_of_fractions_artowner"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="remaining_fractions",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
