# Generated by Django 4.2.10 on 2025-09-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0013_art_category_art_medium_art_type_artreviews"),
    ]

    operations = [
        migrations.AddField(
            model_name="artreviews",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
