# Generated by Django 4.2.10 on 2025-09-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0015_art_currency_art_depth_art_edition_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="network",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
