# Generated by Django 4.2.10 on 2025-09-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0016_art_network"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="enable_vr",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auction",
            name="min_bid_increment",
            field=models.FloatField(default=0),
        ),
    ]
