# Generated by Django 4.2.10 on 2025-09-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0017_art_enable_vr_auction_min_bid_increment"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="buy_now_price",
            field=models.FloatField(default=0),
        ),
    ]
