# Generated by Django 4.2.10 on 2025-09-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0018_auction_buy_now_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="enable_vr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
