# Generated by Django 4.2.10 on 2025-09-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0019_alter_art_enable_vr"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction",
            old_name="starting_price",
            new_name="starting_bid",
        ),
    ]
