# Generated by Django 4.2.10 on 2025-09-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0020_rename_starting_price_auction_starting_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="final_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="reserve_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="starting_bid",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
