# Generated by Django 4.2.10 on 2025-09-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0021_alter_auction_final_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionbid",
            name="amount",
            field=models.FloatField(default=1),
        ),
    ]
