# Generated by Django 4.2.10 on 2025-09-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0022_alter_auctionbid_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="discount_price",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
