# Generated by Django 4.2.10 on 2025-09-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0023_art_discount_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
