# Generated by Django 4.2.10 on 2025-09-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0026_artviewcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="eta",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Transit", "In Transit"),
                    ("Delivered", "Delivered"),
                    ("Canceled", "Canceled"),
                    ("Refunded", "Refunded"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
