# Generated by Django 4.2.10 on 2025-09-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0027_order_eta_order_tracking_id_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="in_transit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
