# Generated by Django 4.2.10 on 2025-10-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0028_order_in_transit_order_order_id_order_shipped_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="artreviews",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="art_reviews",
                to="artist.order",
            ),
        ),
    ]
