# Generated by Django 4.2.10 on 2025-10-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0029_artreviews_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="locations",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
