# Generated by Django 4.2.10 on 2025-10-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0032_artistshop"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistshop",
            name="arts",
            field=models.ManyToManyField(related_name="shop_arts", to="artist.art"),
        ),
    ]
