# Generated by Django 4.2.10 on 2025-10-14 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artist", "0034_alter_order_status_orderdispute_disputedocuments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderdispute",
            name="admin",
        ),
        migrations.AddField(
            model_name="disputechat",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="chat_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderdispute",
            name="buyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispute_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderdispute",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disputes",
                to="artist.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderdispute",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispute_seller",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderdispute",
            name="status",
            field=models.CharField(
                choices=[
                    ("FILED", "FILED"),
                    ("RESOLVED_REFUND", "RESOLVED_REFUND"),
                    ("RESOLVED_RELEASE", "RESOLVED_RELEASE"),
                ],
                default="FILED",
                max_length=200,
            ),
        ),
    ]
