# Generated by Django 4.2.10 on 2025-10-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0035_remove_orderdispute_admin_disputechat_seller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sale_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("In Transit", "In Transit"),
                    ("Shipped", "Shipped"),
                    ("Delivered", "Delivered"),
                    ("Disputed", "Disputed"),
                    ("Completed", "Completed"),
                    ("Canceled", "Canceled"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
