# Generated by Django 4.2.10 on 2025-10-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0036_order_sale_id_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdispute",
            name="admin_remarks",
            field=models.TextField(blank=True, null=True),
        ),
    ]
