# Generated by Django 4.2.10 on 2025-10-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0037_orderdispute_admin_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputechat",
            name="initial_msg",
            field=models.BooleanField(default=False),
        ),
    ]
