# Generated by Django 4.2.10 on 2025-10-16 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0038_disputechat_initial_msg"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputechat",
            name="dispute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dispute_chats",
                to="artist.orderdispute",
            ),
        ),
    ]
