# Generated by Django 4.2.10 on 2025-10-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0039_disputechat_dispute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disputechat",
            name="seller",
        ),
    ]
