# Generated by Django 4.2.10 on 2025-10-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0040_remove_disputechat_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disputechat",
            name="admin",
        ),
    ]
