# Generated by Django 4.2.10 on 2025-10-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0041_remove_disputechat_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="disputechat",
            name="to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
