# Generated by Django 4.2.10 on 2025-10-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0043_disputeconversation_disputemessage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disputemessage",
            name="initial_msg",
        ),
    ]
