# Generated by Django 4.2.10 on 2025-10-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0044_remove_disputemessage_initial_msg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disputeconversation",
            name="party_role",
            field=models.CharField(
                choices=[("BUYER", "Buyer"), ("ARTIST", "ARTIST")], max_length=10
            ),
        ),
    ]
