# Generated by Django 4.2.10 on 2025-10-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0045_alter_disputeconversation_party_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disputeconversation",
            name="party_role",
            field=models.CharField(
                choices=[("BUYER", "Buyer"), ("ARTIST", "Artist")], max_length=10
            ),
        ),
    ]
