# Generated by Django 4.2.10 on 2025-10-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0047_alter_disputeconversation_party_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistshop",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="shop_images/"),
        ),
    ]
