# Generated by Django 4.2.10 on 2025-10-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0049_orderlabel"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="color_palette",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Warm", "Warm Tones"),
                    ("Cool", "Cool Tones"),
                    ("Neutral", "Neutral Tones"),
                    ("Earthy", "Earthy Tones"),
                    ("Oceanic", "Oceanic Tones"),
                ],
                default="Neutral",
                help_text="Dominant color palette of the artwork",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="copy_or_original",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Original", "Original Artwork"),
                    ("Copy", "Reproduction Copy"),
                ],
                default="Original",
                help_text="Is this an original or a copy?",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="delivery_days",
            field=models.IntegerField(
                blank=True,
                default=7,
                help_text="Estimated delivery time in days",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="frame",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                default="No",
                help_text="Does the artwork come with a frame?",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="lighting_requirements",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Natural Light", "Natural Light"),
                    ("Bright Light", "Bright Light"),
                    ("Soft Light", "Soft Light"),
                ],
                default="Natural Light",
                help_text="Recommended lighting for optimal display",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="mood_atmosphere",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Calming", "Calming"),
                    ("Energetic", "Energetic"),
                    ("Joyful", "Joyful"),
                    ("Reflective", "Reflective"),
                    ("Relaxing", "Relaxing"),
                    ("Neutral", "Neutral"),
                ],
                default="Neutral",
                help_text="Emotional mood conveyed by the artwork",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="print_or_real",
            field=models.CharField(
                blank=True,
                choices=[("Real", "Physical Artwork"), ("Print", "Digital Print")],
                default="Real",
                help_text="Physical artwork or print",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="recommended_environment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Living Room", "Living Room"),
                    ("Bedroom", "Bedroom"),
                    ("Office", "Office"),
                    ("Gallery", "Gallery"),
                    ("Kid Room", "Kid Room"),
                    ("Dining Room", "Dining Room"),
                ],
                default="Living Room",
                help_text="Best environment to display this artwork",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="reproduction_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Lithograph", "Lithograph"),
                    ("Screen Print", "Screen Print"),
                    ("Giclee", "Giclée Print"),
                    ("No Value", "No Reproduction"),
                ],
                default="No Value",
                help_text="Type of reproduction technique used (if applicable)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="shipment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Standard", "Standard Shipping"),
                    ("Express", "Express Shipping"),
                    ("Free Shipping", "Free Shipping"),
                ],
                default="Standard",
                help_text="Shipping method for the artwork",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="art",
            name="target_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Collectors", "Art Collectors"),
                    ("Corporate", "Corporate Clients"),
                    ("Young Professionals", "Young Professionals"),
                    ("Interior Designers", "Interior Designers"),
                    ("General Public", "General Public"),
                ],
                default="Collectors",
                help_text="Primary target audience for this artwork",
                max_length=50,
                null=True,
            ),
        ),
    ]
