# Generated by Django 4.2.10 on 2025-10-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0052_alter_artcomment_art_alter_artcomment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="symbol",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
