# Generated by Django 4.2.10 on 2025-10-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0053_art_symbol"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="art",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="art_payouts",
                to="artist.art",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_payouts",
                to="artist.order",
            ),
        ),
    ]
