# Generated by Django 4.2.10 on 2025-10-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0054_payout_art_payout_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="sale_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
