# Generated by Django 4.2.10 on 2025-10-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0055_art_sale_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="release_platform",
            field=models.CharField(default="Crypto wallet", max_length=50),
        ),
    ]
