# Generated by Django 4.2.10 on 2025-11-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0056_payout_release_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="auction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
