# Generated by Django 4.2.10 on 2025-11-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0057_auction_auction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="art",
            name="token_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
