# Generated by Django 4.2.10 on 2025-11-07 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artist", "0058_art_token_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=128)),
                ("category", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, null=True)),
                ("rule", models.CharField(blank=True, max_length=128, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("max_participants", models.IntegerField(default=0)),
                ("reward_amount", models.FloatField(default=0)),
                ("reward_currency", models.CharField(default="Fiat", max_length=10)),
                (
                    "submission_rule",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "challenge_image",
                    models.FileField(
                        blank=True, null=True, upload_to="challenge_images/"
                    ),
                ),
                ("no_of_winners", models.IntegerField(default=0)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ChallengeAttachments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "image",
                    models.FileField(
                        blank=True, null=True, upload_to="challenge_attachments/"
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenge_attachments",
                        to="artist.organizationchallenge",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
