# Generated by Django 4.2.10 on 2025-11-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0061_event_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
