# Generated by Django 4.2.10 on 2025-11-20 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artist", "0062_alter_event_end_date_alter_event_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="auction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="artist.auction",
            ),
        ),
        migrations.AlterField(
            model_name="art",
            name="art_type",
            field=models.CharField(
                choices=[
                    ("Fractional", "Fractional"),
                    ("Single", "Single"),
                    ("Offers", "Offers"),
                ],
                default="Single",
                help_text="Is this a fractional piece or a single-edition work?",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BuyerOffers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("amount", models.PositiveIntegerField(default=0)),
                ("is_accepted", models.BooleanField(default=False)),
                (
                    "art",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="artist.art",
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers_buyer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
