# Generated by Django 4.2.10 on 2025-11-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0063_order_auction_alter_art_art_type_buyeroffers"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="offer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers_order",
                to="artist.buyeroffers",
            ),
        ),
    ]
