# Generated by Django 4.2.10 on 2025-12-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0067_userboard_userboardcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyeroffers",
            name="is_rejected",
            field=models.BooleanField(default=False),
        ),
    ]
