# Generated by Django 4.2.10 on 2025-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0068_buyeroffers_is_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyeroffers",
            name="reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
