# Generated by Django 4.2.10 on 2026-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0071_alter_auction_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="transactions_type",
            field=models.CharField(default="Purchase", max_length=100),
        ),
    ]
