# Generated by Django 4.2.10 on 2025-07-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_role_kycsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Customer", "Customer"),
                    ("Artist", "Artist"),
                    ("SuperAdmin", "SuperAdmin"),
                ],
                default="Customer",
                max_length=100,
            ),
        ),
    ]
