# Generated by Django 4.2.10 on 2025-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_kycsubmission_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycsubmission",
            name="wallet",
            field=models.CharField(default="asdsad", max_length=100),
            preserve_default=False,
        ),
    ]
