# Generated by Django 4.2.10 on 2025-08-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_kycsubmission_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycsubmission",
            name="tx",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
