# Generated by Django 4.2.10 on 2025-09-08 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_user_banner_user_bio_user_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_organization",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Customer", "Customer"),
                    ("Artist", "Artist"),
                    ("SuperAdmin", "SuperAdmin"),
                    ("Organization", "Organization"),
                ],
                default="Customer",
                max_length=100,
            ),
        ),
    ]
