# Generated by Django 4.2.10 on 2025-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_organization_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycsubmission",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="back_image",
            field=models.FileField(blank=True, null=True, upload_to="back_images"),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="First Name"
            ),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="front_image",
            field=models.FileField(blank=True, null=True, upload_to="front_images"),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="id_card",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID Card"
            ),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Last Name"
            ),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Phone Number"
            ),
        ),
    ]
