# Generated by Django 4.2.10 on 2025-09-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_kycsubmission_address_kycsubmission_back_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kycsubmission",
            name="document",
        ),
        migrations.RemoveField(
            model_name="kycsubmission",
            name="notes",
        ),
    ]
