# Generated by Django 4.2.10 on 2025-09-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_remove_kycsubmission_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_contact_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_name",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
