# Generated by Django 4.2.10 on 2025-10-02 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_sellerinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreferenceSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "currency",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "language",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("show_collection", models.BooleanField(default=True)),
                ("show_purchases", models.BooleanField(default=True)),
                ("show_activity", models.BooleanField(default=True)),
                ("allow_messages", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("push", models.BooleanField(default=True)),
                ("email", models.BooleanField(default=True)),
                ("sms", models.BooleanField(default=True)),
                ("newsletter", models.BooleanField(default=True)),
                ("price_alerts", models.BooleanField(default=True)),
                ("auction_reminder", models.BooleanField(default=True)),
                ("event_invites", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
