# Generated by Django 4.2.10 on 2025-10-02 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_preferencesetting_notificationsetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferencesetting",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preference_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
