# Generated by Django 4.2.10 on 2025-10-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_preferencesetting_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preferencesetting",
            name="currency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="preferencesetting",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
