# Generated by Django 4.2.10 on 2025-10-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_alter_preferencesetting_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistPortFolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "external_link",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="portfolio_image"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="interests",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="socials",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.JSONField(default=list),
        ),
    ]
