# Generated by Django 4.2.10 on 2025-10-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_artistportfolio_user_about_user_age_user_interests_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interests",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="socials",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="website",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
