# Generated by Django 4.2.10 on 2025-10-19 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_alter_user_interests_alter_user_socials_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistportfolio",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artists_portfolio",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
