# Generated by Django 4.2.10 on 2025-10-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_artistportfolio_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
