# Generated by Django 4.2.10 on 2025-11-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_verificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verify",
            field=models.BooleanField(default=True),
        ),
    ]
