# Generated by Django 4.2.10 on 2025-11-16 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_final", "0001_initial"),
        ("users", "0024_userverifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="focus",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_step",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_region",
                to="market_final.region",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="try_market",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="years_of_experience",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Customer", "Customer"),
                    ("Artist", "Artist"),
                    ("SuperAdmin", "SuperAdmin"),
                    ("Organization", "Organization"),
                    ("Gallery", "Gallery"),
                    ("Collector", "Collector"),
                    ("Curator", "Curator"),
                    ("Investor", "Investor"),
                ],
                default="Customer",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="KYCVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_number", models.CharField(blank=True, max_length=255, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "postal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gov_issued_id",
                    models.FileField(blank=True, null=True, upload_to="kyc_documents"),
                ),
                (
                    "proof_address",
                    models.FileField(blank=True, null=True, upload_to="kyc_documents"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kyc_verification",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntersetReward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("art_style", models.JSONField(blank=True, default=list, null=True)),
                (
                    "geographic_interset",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "price_interset",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "preferred_time_periods",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("goal_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "points_reward",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
