# Generated by Django 4.2.10 on 2025-11-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_user_focus_user_instagram_handle_user_points_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_referral_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
