# Generated by Django 4.2.10 on 2025-11-25 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_userreferral"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userreferral",
            name="referenced_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenced_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userreferral",
            name="referenced_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenced_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
