# Generated by Django 4.2.10 on 2025-12-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_userreferral_referenced_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="influence_points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
