# Generated by Django 4.2.10 on 2025-12-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_user_influence_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_contract",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
