# Generated by Django 4.2.10 on 2025-12-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_user_influence_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="fann_2fa",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="fann_2fa_otp",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="fann_2fa_otp_created",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
