# Generated by Django 4.2.10 on 2025-12-02 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_user_fann_2fa_user_fann_2fa_otp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgSecuritySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("public_gallery", models.BooleanField(default=False)),
                ("require_artist", models.BooleanField(default=False)),
                ("guest_purchase", models.BooleanField(default=False)),
                ("artist_messaging", models.BooleanField(default=False)),
                ("monthly_analytics", models.BooleanField(default=False)),
                (
                    "financial_setting",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "payment_currency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gallery_configuration", models.BooleanField(default=False)),
                ("direct_sale", models.BooleanField(default=False)),
                ("allow_account", models.BooleanField(default=False)),
                (
                    "artwork_limit",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_security_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
