# Generated by Django 4.2.10 on 2025-12-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_user_user_contract"),
        ("users", "0033_communitychallenge_challengeparticipant"),
    ]

    operations = []
