# Generated by Django 4.2.10 on 2025-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_merge_20251203_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("Admin", "Admin"),
                    ("Customer", "Customer"),
                    ("Artist", "Artist"),
                    ("SuperAdmin", "SuperAdmin"),
                    ("Organization", "Organization"),
                    ("Gallery", "Gallery"),
                    ("Collector", "Collector"),
                    ("Ambassador", "Ambassador"),
                    ("Investor", "Investor"),
                ],
                default="Customer",
                max_length=100,
            ),
        ),
    ]
