# Generated by Django 4.2.10 on 2025-12-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_merge_20251203_0818"),
        ("users", "0035_alter_user_role"),
    ]

    operations = []
