# Generated by Django 4.2.10 on 2025-12-06 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "market_final",
            "0008_instagramfollowers_primaryplatform_tiktokfollowers_and_more",
        ),
        ("users", "0036_merge_0034_merge_20251203_0818_0035_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="content_niche",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="instagram_follower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_insta_follower",
                to="market_final.instagramfollowers",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_platform",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_primary_platform",
                to="market_final.primaryplatform",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tiktok_follower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_tiktok_follower",
                to="market_final.tiktokfollowers",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tiktok_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_follower",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_twitter_follower",
                to="market_final.twitterfollowers",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube_handle",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="youtube_subscribers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_youtube_subscriber",
                to="market_final.youtubesubscribers",
            ),
        ),
    ]
