# Generated by Django 4.2.10 on 2025-12-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_user_content_niche_user_instagram_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_partial_completed",
            field=models.BooleanField(default=False),
        ),
    ]
