# Generated by Django 4.2.10 on 2025-12-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_intersetreward_goal_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="is_kyc_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="intersetreward",
            name="goal_type",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
