# Generated by Django 4.2.10 on 2025-12-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("market_final", "0011_pricerange_alter_artworkcollection_category_and_more"),
        ("users", "0040_kycverification_is_kyc_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="id_type",
            field=models.CharField(
                choices=[
                    ("Passport", "Passport"),
                    ("National ID", "National ID"),
                    ("Emirates ID", "Emirates ID"),
                    ("Iqama (Saudi Residency)", "Iqama (Saudi Residency)"),
                    ("Driver's License", "Driver's License"),
                ],
                default="Passport",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="street_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="artist_statement",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="award_artist",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="education",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_main_contact_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="preferred_commission_rate",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="price_range",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_price_range",
                to="market_final.pricerange",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shipping_preference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="studio_address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
