# Generated by Django 4.2.10 on 2025-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0041_kycverification_id_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exhibition_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="founded_year",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("commercial", "commercial"),
                    ("non_profit", "non_profit"),
                    ("public_museum", "public_museum"),
                    ("private_collection", "private_collection"),
                    ("other", "other"),
                ],
                default="commercial",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="promotion_plan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
