# Generated by Django 4.2.10 on 2025-12-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0042_user_exhibition_count_user_founded_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="gov_issued_id_back",
            field=models.FileField(blank=True, null=True, upload_to="kyc_documents"),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="gov_issued_id_front",
            field=models.FileField(blank=True, null=True, upload_to="kyc_documents"),
        ),
    ]
