# Generated by Django 4.2.10 on 2025-12-19 11:43

from django.db import migrations, models
import json


def convert_points_reward_to_json(apps, schema_editor):
    IntersetReward = apps.get_model("users", "IntersetReward")
    for obj in IntersetReward.objects.all():
        if obj.points_reward:
            try:
                obj.points_reward = json.dumps([obj.points_reward])
            except Exception:
                obj.points_reward = json.dumps([])
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0043_kycverification_gov_issued_id_back_and_more"),
    ]

    operations = [
        migrations.RunPython(convert_points_reward_to_json),
    ]
