# Generated by Django 4.2.10 on 2025-12-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_alter_intersetreward_points_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycsubmission",
            name="country_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kycsubmission",
            name="identity_contract",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="intersetreward",
            name="points_reward",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
