# Generated by Django 4.2.10 on 2025-12-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0044_alter_intersetreward_points_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="intersetreward",
            name="points_reward",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
