# Generated by Django 4.2.10 on 2025-12-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0045_alter_intersetreward_points_reward"),
        ("users", "0045_kycsubmission_country_code_and_more"),
    ]

    operations = []
