# Generated by Django 4.2.10 on 2025-12-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0046_merge_20251222_1452"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="social_link_followers",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="kycverification",
            name="social_link_handler",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
