# Generated by Django 4.2.10 on 2025-12-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0046_merge_20251219_1826"),
        ("users", "0047_kycverification_social_link_followers_and_more"),
    ]

    operations = []
