# Generated by Django 4.2.10 on 2026-01-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0048_merge_20251223_1742"),
    ]

    operations = [
        migrations.AddField(
            model_name="kycverification",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
