# Generated by Django 4.2.10 on 2026-01-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0049_kycverification_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kycverification",
            old_name="nationality",
            new_name="country",
        ),
        migrations.AddField(
            model_name="kycverification",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
