# Generated by Django 4.2.10 on 2026-01-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0051_userwithdrawrequests"),
    ]

    operations = [
        migrations.AddField(
            model_name="userwithdrawrequests",
            name="status",
            field=models.CharField(default="Pending", max_length=100),
        ),
    ]
