# Generated by Django 4.2.10 on 2026-01-23 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0052_userwithdrawrequests_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=2)),
                ("bank_city", models.CharField(max_length=120)),
                ("bank_name", models.CharField(max_length=255)),
                ("nick_name", models.CharField(blank=True, max_length=120, null=True)),
                ("bic_swift", models.CharField(max_length=11)),
                ("account_number", models.CharField(max_length=64)),
                ("bank_holder_name", models.CharField(max_length=255)),
                ("street_address", models.CharField(max_length=255)),
                ("zip_code", models.CharField(max_length=20)),
                ("city", models.CharField(max_length=120)),
                (
                    "state_province",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_banks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bank_accounts",
                "indexes": [
                    models.Index(
                        fields=["country"], name="bank_accoun_country_5dbda9_idx"
                    ),
                    models.Index(
                        fields=["bic_swift"], name="bank_accoun_bic_swi_706ee8_idx"
                    ),
                    models.Index(
                        fields=["account_number"], name="bank_accoun_account_a5c8c7_idx"
                    ),
                ],
            },
        ),
    ]
