# Generated by Django 4.2.10 on 2026-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0053_bankaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bankaccount",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
