# Generated by Django 4.2.10 on 2026-06-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_bankaccount_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Customer', 'Customer'), ('Artist', 'Artist'), ('SuperAdmin', 'SuperAdmin'), ('Organization', 'Organization'), ('Gallery', 'Gallery'), ('Collector', 'Collector'), ('Ambassador', 'Ambassador'), ('Investor', 'Investor'), ('Curator', 'Curator')], default='Customer', max_length=100),
        ),
    ]
