# Generated by Django 4.2.10 on 2026-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0055_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='application_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
