# Generated by Django 4.2.10 on 2026-07-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_user_application_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acquisition_source',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
