# Generated by Django 4.2.10 on 2026-07-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_user_acquisition_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='intersetreward',
            name='buying_frequency',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='intersetreward',
            name='mediums',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='intersetreward',
            name='preferred_spaces',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
