# Generated by Django 4.2.10 on 2025-11-28 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market_final", "0004_redemption_userredemption"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_notification", models.BooleanField(default=False)),
                ("push_notification", models.BooleanField(default=False)),
                ("referral_update", models.BooleanField(default=False)),
                ("reward_milestone", models.BooleanField(default=False)),
                ("artwork_alert", models.BooleanField(default=False)),
                ("msg_comment", models.BooleanField(default=False)),
                ("profile_visibility", models.BooleanField(default=False)),
                ("show_email", models.BooleanField(default=False)),
                ("show_phone", models.BooleanField(default=False)),
                ("show_location", models.BooleanField(default=False)),
                ("language", models.CharField(blank=True, max_length=100, null=True)),
                ("theme", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "profile_timezone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "preferred_currency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_fann_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
