# Generated by Django 4.2.10 on 2025-12-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "market_final",
            "0008_instagramfollowers_primaryplatform_tiktokfollowers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="artistroaster",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
