# Generated by Django 4.2.10 on 2025-12-08 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market_final", "0009_artistroaster_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="PuzzleCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_puzzle_complete",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
