# Generated by Django 4.2.10 on 2025-12-12 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market_final", "0010_puzzlecompletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceRange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="artworkcollection",
            name="category",
            field=models.CharField(
                choices=[
                    ("Contemporary", "Contemporary"),
                    ("Digital", "Digital"),
                    ("Traditional", "Traditional"),
                    ("Photography", "Photography"),
                    ("Sculpture", "Sculpture"),
                ],
                default="Contemporary",
                max_length=100,
            ),
        ),
        migrations.CreateModel(
            name="ArtworkArtistCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="artwork_artist_images"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("price", models.CharField(blank=True, max_length=200, null=True)),
                ("dimensions", models.CharField(blank=True, max_length=200, null=True)),
                ("medium", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("no_artist", models.PositiveIntegerField(default=0)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Gallery", "Gallery"), ("Artist", "Artist")],
                        default="Artist",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_in_artwork_artist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
