# Generated by Django 4.2.10 on 2025-12-18 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("market_final", "0011_pricerange_alter_artworkcollection_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReportBug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("severity", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "device_info",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "bug_category",
                    models.CharField(
                        choices=[
                            ("UI/UX Issue", "UI/UX Issue"),
                            ("Performance", "Performance"),
                            ("Functionality", "Functionality"),
                            ("Security", "Security"),
                            ("Data Issue", "Data Issue"),
                            ("other", "other"),
                        ],
                        default="UI/UX Issue",
                        max_length=100,
                    ),
                ),
                (
                    "bug_image",
                    models.FileField(blank=True, null=True, upload_to="Report_Bug"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_in_report_bug",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("describe_idea", models.TextField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "feedback_category",
                    models.CharField(
                        choices=[
                            ("New Feature", "New Feature"),
                            ("Improvement", "Improvement"),
                            ("Integration", "Integration"),
                            ("User Experience", "User Experience"),
                            ("Community Features", "Community Features"),
                            ("other", "other"),
                        ],
                        default="New Feature",
                        max_length=100,
                    ),
                ),
                (
                    "feedback_about",
                    models.CharField(
                        choices=[
                            ("Performance Experience", "Performance Experience"),
                            ("Features & Functionality", "Features & Functionality"),
                            ("Design & Interface", "Design & Interface"),
                            ("Performance & Speed", "Performance & Speed"),
                            ("Customer Support", "Customer Support"),
                            ("other", "other"),
                        ],
                        default="Performance Experience",
                        max_length=100,
                    ),
                ),
                ("sentiment", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_in_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
