# Generated by Django 4.2.10 on 2025-12-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_final", "0012_userreportbug_userfeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artworkartistcollection",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Gallery", "Gallery"),
                    ("Artist", "Artist"),
                    ("Collector", "Collector"),
                ],
                default="Artist",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="feedback_about",
            field=models.CharField(
                choices=[
                    ("Performance Experience", "Performance Experience"),
                    ("Features & Functionality", "Features & Functionality"),
                    ("Design & Interface", "Design & Interface"),
                    ("Performance & Speed", "Performance & Speed"),
                    ("Customer Support", "Customer Support"),
                    ("Other", "Other"),
                ],
                default="Performance Experience",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userfeedback",
            name="feedback_category",
            field=models.CharField(
                choices=[
                    ("New Feature", "New Feature"),
                    ("Improvement", "Improvement"),
                    ("Integration", "Integration"),
                    ("User Experience", "User Experience"),
                    ("Community Features", "Community Features"),
                    ("Other", "Other"),
                ],
                default="New Feature",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="userreportbug",
            name="bug_category",
            field=models.CharField(
                choices=[
                    ("UI/UX Issue", "UI/UX Issue"),
                    ("Performance", "Performance"),
                    ("Functionality", "Functionality"),
                    ("Security", "Security"),
                    ("Data Issue", "Data Issue"),
                    ("Other", "Other"),
                ],
                default="UI/UX Issue",
                max_length=100,
            ),
        ),
    ]
