# Generated by Django 4.2.10 on 2025-12-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market_final", "00014_data_seed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="profile_visibility",
            field=models.BooleanField(default=True),
        ),
    ]
