# Generated by Django 4.2.10 on 2025-08-15 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaintingAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="paintings/")),
                (
                    "predicted_authenticity",
                    models.CharField(
                        choices=[
                            ("real", "Real"),
                            ("fake", "Fake"),
                            ("replica", "Replica"),
                            ("uncertain", "Uncertain"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("analysis_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "artist_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "artwork_title",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "estimated_period",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "ordering": ["-analysis_timestamp"],
            },
        ),
    ]
