# Generated by Django 4.2.10 on 2025-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyer", "0002_userpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("payment_type", models.CharField(max_length=100)),
                ("card_holder_name", models.CharField(max_length=100)),
                ("cvv", models.CharField(max_length=100)),
                ("card_number", models.CharField(max_length=100)),
                ("date", models.CharField(max_length=100)),
                ("is_primary", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
