# Generated by Django 4.2.10 on 2026-06-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0003_seed_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleprofile',
            name='admin_override_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='whitelistentry',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
    ]
