# Generated by Django 4.2.10 on 2026-06-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0004_roleprofile_admin_override_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_en', models.CharField(max_length=140)),
                ('title_ar', models.CharField(blank=True, max_length=140)),
                ('body_en', models.TextField(blank=True)),
                ('body_ar', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
