# Generated by Django 4.2.10 on 2026-07-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0005_announcement_task_publish_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='usertask',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertask',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('failed', 'Quiz failed (retryable)')], default='pending', max_length=16),
        ),
    ]
