# Generated by Django 4.2.10 on 2026-07-23 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualification', '0008_conciergerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('session_id', models.CharField(blank=True, max_length=64)),
                ('consent_type', models.CharField(choices=[('analytics', 'Analytics'), ('marketing', 'Marketing'), ('terms', 'Terms')], max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('granted', models.BooleanField(default=False)),
                ('double_opt_in_required', models.BooleanField(default=False)),
                ('double_opt_in_confirmed', models.BooleanField(default=False)),
                ('confirm_token', models.CharField(blank=True, max_length=64)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=60)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['consent_type', 'created_at'], name='qualificati_consent_171d53_idx')],
            },
        ),
    ]
